name: projek_pam5
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_rating_bar: 4.0.1
  dots_indicator: 2.1.0
  pin_code_fields: 7.4.0
  animated_text_kit: 4.2.2
  badges: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
  - assets/icons/
  - assets/images/
  uses-material-design: true

